BugTracker/Models/Domain/TicketType.cs
using System;
using System.Collections.Generic;

namespace BugTracker.Models.Domain
{
    public class TicketType
    {
        public string Id { get; set; }
        public string TypeName { get; set; }

        public virtual List<Ticket> Tickets { get; set; }

        public TicketType()
        {
            Id = Guid.NewGuid().ToString();
            Tickets = new List<Ticket>();
        }
    }
}

BugTracker/Models/ViewModels/EditAttachmentsViewModel.cs
using System.Collections.Generic;
using System.Web;

namespace BugTracker.Models.ViewModels
{
    public class EditAttachmentsViewModel
    {
        public string TicketId { get; set; }
        public List<string> MediaUrls { get; set; }
        public List<HttpPostedFileBase> Files { get; set; }
        public bool AvailableForUser { get; set; }

        public EditAttachmentsViewModel()
        {
            Files = new List<HttpPostedFileBase>();
        }
    }
}

BugTracker/Controllers/CommentsController.cs
using BugTracker.Models;
using BugTracker.Models.Domain;
using BugTracker.Models.Helpers;
using BugTracker.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BugTracker.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext DbContext;
        private RolesAndUsersHelper RolesAndUsersHelper;        


        public CommentsController()
        {
            DbContext = new ApplicationDbContext();
            RolesAndUsersHelper = new RolesAndUsersHelper(DbContext);
        }


        [HttpPost]
        [Authorize(Roles = "Admin, Project Manager, Developer, Submitter")]
        public async Task<ActionResult> CreateComment(IndexTicketViewModel formdata, string ticketId)
        {
            var currentUserId = User.Identity.GetUserId();
            var ticket = DbContext.Tickets.FirstOrDefault(p => p.Id == ticketId);
            if (ticket == null || ticket.Project.Archived == true)
            {
                return RedirectToAction("AllTickets", "Tickets");
            }
            var currentUser = DbContext.Users.FirstOrDefault(p => p.Id == currentUserId);


            var isUserAssigned = ticket.AssignedMembers.Any(p => p.Id == currentUserId);
            var isUserOwner = ticket.TicketOwnerId == currentUserId;
            var isUserADeveloperAndSubmitter = User.IsInRole("Developer") && User.IsInRole("Submitter");

            if (!User.IsInRole("Admin") && !User.IsInRole("Project Manager"))
            {

                if (isUserADeveloperAndSubmitter && !isUserAssigned && !isUserOwner)
                {
                    return RedirectToAction("ViewTicket", "Tickets", new { id = ticketId });
                }
                else if (User.IsInRole("Developer") && !isUserAssigned && !User.IsInRole("Submitter"))
                {
                    return RedirectToAction("ViewTicket", "Tickets", new { id = ticketId });
                }
                else if (User.IsInRole("Submitter") && !isUserOwner && !User.IsInRole("Developer"))
                {
                    return RedirectToAction("ViewTicket", "Tickets", new { id = ticketId });
                }
            }


            var comment = new Comment();
            comment.CommentCreatorId = currentUserId;
            comment.TicketId = ticketId;
            comment.CommentData = formdata.CommentData;

            ticket.Comments.Add(comment);
            currentUser.Comments.Add(comment);

            DbContext.Comments.Add(comment);

            DbContext.SaveChanges();

            await RolesAndUsersHelper.MassEmailSender(ticket.Id, "Modify");

            return RedirectToAction("ViewTicket", "Tickets", new { id = ticketId });
        }


        [HttpGet]
        [Authorize(Roles = "Admin, Project Manager, Submitter")]
        public ActionResult _EditComment(string commentId)
        {
            if (commentId == null)
            {
                return RedirectToAction("AllTickets", "Tickets");
            }

            var currentUserId = User.Identity.GetUserId();
            var currentUser = DbContext.Users.FirstOrDefault(p => p.Id == currentUserId);
            var comment = DbContext.Comments.FirstOrDefault(p => p.Id == commentId);
            var ticket = DbContext.Tickets.FirstOrDefault(p => p.Comments.Any(r => r.Id == comment.Id));

            if (currentUser == null || comment == null || ticket == null || ticket.Project.Archived == true || (comment.CommentCreatorId != currentUserId && !User.IsInRole("Admin") && !User.IsInRole("Project Manager")))
            {
                return RedirectToAction("AllTickets", "Tickets");
            }

            var model = new CreateEditCommentViewModel();
            model.CommentData = comment.CommentData;
            model.CommentId = comment.Id;
            model.TicketId = ticket.Id;

            return View(model);
        }


        [HttpPost]
        [Authorize(Roles = "Admin, Project Manager, Submitter")]
        public async Task<ActionResult> _EditComment(CreateEditCommentViewModel formData)
        {
            if (formData == null)
            {
                return RedirectToAction("AllTickets", "Tickets");
            }

            var comment = DbContext.Comments.FirstOrDefault(p => p.Id == formData.CommentId);
            var ticket = DbContext.Tickets.FirstOrDefault(p => p.Id == formData.TicketId);
            var currentUserId = User.Identity.GetUserId();
            var currentUser = DbContext.Users.FirstOrDefault(p => p.Id == currentUserId);

            if (comment == null || ticket == null || ticket.Project.Archived == true || formData.CommentData == null || (comment.CommentCreatorId != currentUserId && !User.IsInRole("Admin") && !User.IsInRole("Project Manager")))
            {
                return RedirectToAction("AllTickets", "Tickets");
            }

            comment.CommentData = formData.CommentData;
            comment.DateUpdated = DateTime.Now;

            DbContext.SaveChanges();

            await RolesAndUsersHelper.MassEmailSender(ticket.Id, "Modify");

            return RedirectToAction("ViewTicket", "Tickets", new { id = ticket.Id });
        }


        [HttpPost]
        [Authorize(Roles = "Admin, Project Manager, Submitter")]
        public ActionResult DeleteComment(string commentId)
        {
            if (commentId == null)
            {
                return RedirectToAction("AllTickets", "Tickets");
            }
            var comment = DbContext.Comments.FirstOrDefault(p => p.Id == commentId);
            var currentUserId = User.Identity.GetUserId();
            var currentUser = DbContext.Users.FirstOrDefault(p => p.Id == currentUserId);
            var ticket = DbContext.Tickets.FirstOrDefault(p => p.Comments.Any(r => r.Id == comment.Id));

            if (ticket == null || ticket.Project.Archived == true || comment == null)
            {
                return RedirectToAction("ViewTicket", "Tickets", new { ticketId = ticket.Id });
            }

            ticket.Comments.Remove(comment);
            if (comment.CommentCreatorId == currentUserId)
            {
                currentUser.Comments.Remove(comment);
            }
            DbContext.Comments.Remove(comment);

            DbContext.SaveChanges();

            return RedirectToAction("ViewTicket", "Tickets", new { id = ticket.Id });
        }
       
    }
}

BugTracker/Controllers/TicketsController.cs
using BugTracker.Models;
using BugTracker.Models.Domain;
using BugTracker.Models.Helpers;
using BugTracker.Models.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BugTracker.Controllers
{
    public class TicketsController : Controller
    {
        private ApplicationDbContext DbContext;
        private RolesAndUsersHelper RolesAndUsersHelper;
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public TicketsController()
        {
            DbContext = new ApplicationDbContext();
            RolesAndUsersHelper = new RolesAndUsersHelper(DbContext);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, Project Manager, Developer, Submitter")]
        public ActionResult AllTickets()
        {
            string currentUserId = User.Identity.GetUserId();
            List<IndexTicketViewModel> viewModel;
            if (User.IsInRole("Admin") || User.IsInRole("Project Manager"))
            {
                viewModel = DbContext.Tickets
                    .Where(p => p.Project.Archived == false)
                    .Select(
                    ticket => new IndexTicketViewModel
                    {
                        Id = ticket.Id,
                        TicketTitle = ticket.TicketTitle,
                        TicketDescription = ticket.TicketDescription,
                        TicketType = ticket.TicketType.TypeName,
                        TicketPriority = ticket.TicketPriority.PriorityLevel,
                        TicketStatus = ticket.TicketStatus.StatusName,
                        DateCreated = ticket.DateCreated,
                        DateUpdated = ticket.DateUpdated,
                        TicketOwner = new ProjectMemberViewModel()
                        {
                            Id = ticket.TicketOwnerId,
                            NameOfUser = ticket.TicketOwner.NameOfUser,
                            Roles = (from userRoles in ticket.TicketOwner.Roles
                                     join roles in DbContext.Roles
                                     on userRoles.RoleId equals roles.Id
                                     select roles.Name).ToList()
                        },
                        TicketAssignees = ticket.AssignedMembers
                        .Select(selectuser => new ProjectMemberViewModel
                        {
                            Id = selectuser.Id,
                            NameOfUser = selectuser.NameOfUser,
                            Roles = (from userRoles in selectuser.Roles
                                     join roles in DbContext.Roles on userRoles.RoleId equals roles.Id
                                     select roles.Name).ToList()
                        }).ToList(),
                        TicketNonAssignees = DbContext.Users
                        .Where(p => !p.AssignedTickets.Any(r => r.Id == ticket.Id))
                        .Select(selectuser => new ProjectMemberViewModel
                        {
                            Id = selectuser.Id,
                            NameOfUser = selectuser.NameOfUser,
                            Roles = (from userRoles in selectuser.Roles
                                     join roles in DbContext.Roles on userRoles.RoleId equals roles.Id
                                     select roles.Name).ToList()
                        })
                        .ToList(),
                        ProjectId = ticket.ProjectId,
                        ProjectName = ticket.Project.ProjectName,
                        AvailableForUser = true
                    }).ToList();
            }
            else if (User.IsInRole("Developer") && User.IsInRole("Submitter"))
            {
                viewModel = DbContext.Tickets
                .Where(p => p.Project.Archived == false && ((p.Project.Users.Any(r => r.Id == currentUserId) && p.AssignedMembers.Any(r => r.Id == currentUserId) && p.TicketOwnerId == currentUserId) || (p.Project.Users.Any(r => r.Id == currentUserId) && p.AssignedMembers.Any(r => r.Id == currentUserId) && p.TicketOwnerId != currentUserId) || (p.Project.Users.Any(r => r.Id == currentUserId) && !p.AssignedMembers.Any(r => r.Id == currentUserId) && p.TicketOwnerId == currentUserId) || (p.TicketOwnerId == currentUserId && p.AssignedMembers.Any(r => r.Id == currentUserId) && !p.Project.Users.Any(r => r.Id == currentUserId)) || (p.Project.Users.Any(r => r.Id == currentUserId) || p.AssignedMembers.Any(r => r.Id == currentUserId) || p.TicketOwnerId == currentUserId)))
                .Select(
                    ticket => new IndexTicketViewModel
                    {
                        Id = ticket.Id,
                        TicketTitle = ticket.TicketTitle,
                        TicketDescription = ticket.TicketDescription,
                        TicketType = ticket.TicketType.TypeName,
                        TicketPriority = ticket.TicketPriority.PriorityLevel,
                        TicketStatus = ticket.TicketStatus.StatusName,
                        DateCreated = ticket.DateCreated,
                        DateUpdated = ticket.DateUpdated,
                        TicketOwner = new ProjectMemberViewModel()
                        {
                            Id = ticket.TicketOwnerId,
                            NameOfUser = ticket.TicketOwner.NameOfUser,
                            Roles = (from userRoles in ticket.TicketOwner.Roles
                                     join roles in DbContext.Roles
                                     on userRoles.RoleId equals roles.Id
                                     select roles.Name).ToList()
                        },
                        TicketAssignees = ticket.AssignedMembers
                        .Select(selectuser => new ProjectMemberViewModel
                        {
                            Id = selectuser.Id,
                            NameOfUser = selectuser.NameOfUser,
                            Roles = (from userRoles in selectuser.Roles
                                     join roles in DbContext.Roles on userRoles.RoleId equals roles.Id
                                     select roles.Name).ToList()
                        }).ToList(),
                        TicketNonAssignees = DbContext.Users
                        .Where(p => !p.AssignedTickets.Any(r => r.Id == ticket.Id))
                        .Select(selectuser => new ProjectMemberViewModel
                        {
                            Id = selectuser.Id,
                            NameOfUser = selectuser.NameOfUser,
                            Roles = (from userRoles in selectuser.Roles
                                     join roles in DbContext.Roles on userRoles.RoleId equals roles.Id
                                     select roles.Name).ToList()
                        })
                        .ToList(),
                        ProjectId = ticket.ProjectId,
                        ProjectName = ticket.Project.ProjectName,
                        AvailableForUser = ticket.TicketOwnerId == currentUserId || ticket.AssignedMembers.Any(w => w.Id == currentUserId)
                    }).ToList();
            }
            else if (User.IsInRole("Developer"))
            {
                viewModel = DbContext.Tickets
                .Where(p => p.Project.Archived == false && (p.Project.Users.Any(r => r.Id == currentUserId) && p.AssignedMembers.Any(r => r.Id == currentUserId)) || (p.Project.Users.Any(r => r.Id == currentUserId) || p.AssignedMembers.Any(r => r.Id == currentUserId)))
                .Select(
                    ticket => new IndexTicketViewModel
                    {
                        Id = ticket.Id,
                        TicketTitle = ticket.TicketTitle,
                        TicketDescription = ticket.TicketDescription,
                        TicketType = ticket.TicketType.TypeName,
                        TicketPriority = ticket.TicketPriority.PriorityLevel,
                        TicketStatus = ticket.TicketStatus.StatusName,
                        DateCreated = ticket.DateCreated,
                        DateUpdated = ticket.DateUpdated,
                        TicketOwner = new ProjectMemberViewModel()
                        {
                            Id = ticket.TicketOwnerId,
                            NameOfUser = ticket.TicketOwner.NameOfUser,
                            Roles = (from userRoles in ticket.TicketOwner.Roles
                                     join roles in DbContext.Roles
                                     on userRoles.RoleId equals roles.Id
                                     select roles.Name).ToList()
                        },
                        TicketAssignees = ticket.AssignedMembers
                        .Select(selectuser => new ProjectMemberViewModel
                        {
                            Id = selectuser.Id,
                            NameOfUser = selectuser.NameOfUser,
                            Roles = (from userRoles in selectuser.Roles
                                     join roles in DbContext.Roles on userRoles.RoleId equals roles.Id
                                     select roles.Name).ToList()
                        }).ToList(),
                        TicketNonAssignees = DbContext.Users
                        .Where(p => !p.AssignedTickets.Any(r => r.Id == ticket.Id))
                        .Select(selectuser => new ProjectMemberViewModel
                        {

BugTracker/Views/Tickets/AllTickets.cshtml
@model List<IndexTicketViewModel>

@{
    ViewBag.Title = "AllTickets";
}

@section css {
    <link rel="stylesheet"
          href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
}

@section Scripts {
    <script type="text/javascript"
            src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js">
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#tickets-table').DataTable();
        });
    </script>
}

<h2>All Tickets</h2>

<script>
    function writer(parameter) {
        document.write(parameter);
    }

    function extractor(suppliedList) {

        var data = JSON.parse(suppliedList);

        var p = "";
        for (var i = 0; i < data.length; i++) {
            p += data[i].NameOfUser;
            if (i < (data.length - 1)) {
                p += ","
            }
        }

        return p;
    }
</script>

@if (Model != null)
{
    <table id="tickets-table" class="table table-striped">
        <thead>
            <tr>
                <th>Project</th>
                <th>Title</th>
                <th>Assigned Developers</th>
                <th>Created</th>
                <th>Updated</th>
                <th>Type</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Created By</th>
                <th></th>
                @if (User.IsInRole("Admin") || User.IsInRole("Project Manager"))
                {
                    <th></th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var element in Model)
            {
                <tr>
                    <td>
                        <a href="@Url.Action("DetailsOfProject", "Main", new { id = element.ProjectId })">@element.ProjectName</a>
                    </td>
                    <td>
                        <a href="@Url.Action("ViewTicket", "Tickets", new { id = element.Id })">
                            @element.TicketTitle
                        </a>
                    </td>
                    <td>
                        <script>
                          var model = '@Html.Raw(Json.Encode(element.TicketAssignees))';

                          writer(extractor(model));
                        </script>
                    </td>
                    <td>@element.DateCreated</td>
                    <td>@element.DateUpdated</td>
                    <td>@element.TicketType</td>
                    <td>@element.TicketPriority</td>
                    <td>@element.TicketStatus</td>
                    <td>@element.TicketOwner.NameOfUser</td>
                    <td>
                        @if (element.AvailableForUser == true)
                        {
                            <a href="@Url.Action("_EditTicket", "Tickets", new { ticketId = element.Id })">
                                Edit
                            </a>
                        }
                    </td>
                    @if (User.IsInRole("Admin") || User.IsInRole("Project Manager"))
                    {
                        <td>
                            <a href="@Url.Action("ManageTicketMembers", "Tickets", new { ticketId = element.Id })">
                                Manage
                            </a>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
}

BugTracker/Views/Tickets/EditAttachments.cshtml
@model EditAttachmentsViewModel

<h2>Attachments</h2>

@foreach (var file in Model.MediaUrls)
{
    <img class="img-responsive" src="@Url.Content(file)" />
    <form method="post" action="@Url.Action("DeleteAttachments", "Tickets", new { filename = file, ticketId = Model.TicketId })">
        <a href="#" class="btn-delete">Delete</a>
    </form>
}

<form method="post" action="@Url.Action("AddAttachments", "Tickets", new { ticketId = Model.TicketId })" enctype="multipart/form-data">
    <div class="form-group">
        <input type="file" name="Files" multiple required />
    </div>
    <a href="#" class="btn-delete">Add</a>
</form>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(function () {
        $(".btn-delete").on('click', function (e) {
            e.preventDefault();
            $(this).closest('form').submit();
        });
    });
</script>

BugTracker/Views/Tickets/ManageTicketMembers.cshtml
@model ManageTicketMembersViewModel

@{
    ViewBag.Title = "ManageMembers";
}

@section css {
    <link rel="stylesheet"
          href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
}

@section Scripts {
    <script type="text/javascript"
            src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js">
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.manage-members-table').DataTable();
        });
    </script>
}

<h2>Manage developers for ticket: @Model.TicketName</h2>


<h4>Assigned developers:</h4>

<table class="manage-members-table table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Roles</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.CurrentMembers.Count(); i++)
        {
            <tr>
                <td>@Model.CurrentMembers[i].NameOfUser</td>
                <td>
                    @if (Model.CurrentMembers[i].Roles.Count() > 0)
                    {
                        var stringRoles = "";
                        for (var j = 0; j < Model.CurrentMembers[i].Roles.Count(); j++)
                        {
                            stringRoles += Model.CurrentMembers[i].Roles[j];
                            if (j != (Model.CurrentMembers[i].Roles.Count() - 1))
                            {
                                stringRoles += ",";
                                stringRoles += " ";
                            }
                        }
                        <span>@stringRoles</span>;
                    }
                </td>

                <td>
                    <form method="post" action="@Url.Action("ToggleTicketDeveloper", "Tickets", new { ticketId = Model.TicketId, userId = Model.CurrentMembers[i].Id, operation = "Remove" })">
                        <a href="#" class="btn-manager">Remove</a>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<h4>Available developers:</h4>

<table class="manage-members-table table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Roles</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.AllUsers.Count(); i++)
        {
            <tr>
                <td>@Model.AllUsers[i].NameOfUser</td>
                <td>
                    @if (Model.AllUsers[i].Roles.Count() > 0)
                    {
                        var stringRoles = "";
                        for (var j = 0; j < Model.AllUsers[i].Roles.Count(); j++)
                        {
                            stringRoles += Model.AllUsers[i].Roles[j];
                            if (j != (Model.AllUsers[i].Roles.Count() - 1))
                            {
                                stringRoles += ",";
                                stringRoles += " ";
                            }
                        }
                        <span>@stringRoles</span>;
                    }
                </td>

                <td>
                    <form method="post" action="@Url.Action("ToggleTicketDeveloper", "Tickets", new { ticketId = Model.TicketId, userId = Model.AllUsers[i].Id, operation = "Add" })">
                        <a href="#" class="btn-manager">Add</a>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>


<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(function () {
        $(".btn-manager").on('click', function (e) {
            e.preventDefault();
            $(this).closest('form').submit();
        });
    });
</script>

BugTracker/Views/Tickets/ViewTicket.cshtml
@model IndexTicketViewModel

@{
    ViewBag.Title = "ViewTicket";
}

<h4>@Model.TicketTitle</h4>

<div>
    Description:
    <p>@Model.TicketDescription</p>
    <p>Type: @Model.TicketType</p>
    <p>Priority: @Model.TicketPriority</p>
    <p>Status: @Model.TicketStatus</p>
</div>
<p>Created: @Model.DateCreated</p>
<p>Updated: @Model.DateUpdated</p>
<p>Project: @Model.ProjectName</p>
<p>Assigned Members: @Model.TicketAssignees.Count()</p>
<p>Created By: @Model.TicketOwner.NameOfUser</p>
<p><a href="@Url.Action("EditAttachments", "Tickets", new { ticketId = Model.Id })">Attachments</a></p>

<div class="row">
    <div class="col-md-2">
        @foreach (var image in Model.MediaUrls)
        {
            <img class="img-responsive" src="@Url.Content(image)" />
        }
    </div>
</div>

<div>
    @foreach (var history in Model.TicketHistories)
    {
        <div style="border: 2px solid blue; margin-top: 15px; padding-left: 10px; padding-right: 10px">
            <p>Change made by @history.UserName</p>
            <p>Date: @history.DateUpdated</p>
            @foreach (var change in history.Changes)
            {
                <p>@change</p>
            }
        </div>
    }
</div>

@if (Model.AvailableForUser)
{
    <form method="post" action="@Url.Action("CreateComment", "Comments", new { ticketId = Model.Id })">
        <div class="form-group">
            @Html.LabelFor(input => input.CommentData, "Comment")
            @Html.TextAreaFor(input => input.CommentData, new { @class = "form-control", placeholder = "" })
            @Html.ValidationMessageFor(input => input.CommentData)
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
}

<div>
    @for (var comment = 0; comment < Model.Comments.Count(); comment++)
    {
        <p class="each-comment">@Model.Comments[comment].CommentData</p>
        if (Model.Comments[comment].AvailableForUser == true)
        {
            <form method="post" action="@Url.Action("DeleteComment", "Comments", new { commentId = Model.Comments[comment].CommentId })">
                <a href="#" class="btn-delete-comment">Delete Comment</a>
            </form>

            <a id="@Model.Comments[comment].CommentId" class="@Model.Id" data-toggle="modal" href="#@Model.Id" onclick="ModalContentFetcher()">Edit</a>
        }
    }
</div>

<div>
    <div id="@Model.Id" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Edit Comment</h4>
                </div>
                <div class="modal-body" id="modalsbody">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(function () {
        $(".btn-delete-comment").on('click', function (e) {
            e.preventDefault();
            $(this).closest('form').submit();
        });
    });


    let htmlModalCaller = document.querySelector('.@Model.Id');
    function DomAdder(element) {
        var domelement = document.querySelector(".modal-body");
        return domelement.insertAdjacentHTML('afterbegin', element);
    }

    function ModalContentFetcher() {
        return fetch(`../../Comments/_EditComment/?commentId=${htmlModalCaller.id}`,
        {
            method: "Get"
        }).then(
            function(response) {
                if (response.status !== 200) {
                    console.log('Looks like there was a problem. Status Code: ' +
                        response.status);
                    return;
                }

                response.text().then(function (data) {
                    DomAdder(data);
                });
            }
        )
        .catch(function (err) {
                console.log('Fetch Error :-S', err);
        });
    }
</script>

BugTracker/Views/Tickets/_CreateTicket.cshtml
@model CreateEditTicketViewModel

@{
    Layout = null;
}

<h2>Ticket</h2>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<h2>Create New Ticket</h2>

<form method="post" enctype="multipart/form-data" @**@ action="@Url.Action("_CreateTicket", "Tickets")">
    @Html.ValidationSummary(true)
    <div class="form-group">
        @Html.LabelFor(input => input.TicketTitle, "Ticket Name")
        @Html.TextBoxFor(input => input.TicketTitle, new { @class = "form-control", placeholder = "Name" })
        @Html.ValidationMessageFor(input => input.TicketTitle)
    </div>
    @Html.HiddenFor(p => p.ProjectId)


    <div class="form-group">
        @Html.LabelFor(input => input.TicketDescription, "Ticket Details")
        @Html.TextAreaFor(input => input.TicketDescription, new { @class = "form-control", placeholder = "Details" })
        @Html.ValidationMessageFor(input => input.TicketDescription)
    </div>


    <div class="form-group">
        @Html.LabelFor(input => input.TicketType, "Ticket Type")
        @Html.DropDownListFor(input => input.TicketType, new SelectList(Model.DropDownForTypes), "Select Type")
        @Html.ValidationMessageFor(input => input.TicketType)
    </div>


    <div class="form-group">
        @Html.LabelFor(input => input.TicketPriority, "Ticket Priority")
        @Html.DropDownListFor(input => input.TicketPriority, new SelectList(Model.DropDownForPriorities), "Specify Priority")
        @Html.ValidationMessageFor(input => input.TicketPriority)
    </div>

    <div class="form-group">
        <input type="file" name="Media" multiple />
    </div>

    <button type="submit" class="btn btn-default">Submit</button>
</form>